name: Markdown link check

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 9 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  markdown-link-check:
    name: Check Markdown links
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Check Markdown links
        uses: tcort/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          config-file: ".github/mlc_config.json"
          folder-path: "."
